### ISSUE TITLE
Special characters not accepted by foodbot when rating

### ISSUE THREAD

**Issue by andela-kanyanwu** [andela-kanyanwu/food-bot-review#54]
A user tried to rate and comment, but had issues because of multiple dots in the sentence. Foodbot should be able to accept this type of sentence. I think this is why foodbot went offline earlier today. Screenshot below.

<img width="937" alt="screen shot 2016-01-25 at 2 07 02 pm" src="https://cloud.githubusercontent.com/assets/10073270/12552027/465313c0-c36f-11e5-8bbd-b0d74d24cad0.png">

**Comment by andela-kanyanwu** [comment]
It also breaks when other punctuation marks are added.

**Comment by andela-kanyanwu** [comment]
With an input string as `rate breakfast 1 2 It’s quite small`, the error in the log shows ==>
```
Traceback (most recent call last):
  File "./rtmbot.py", line 181, in main_loop
    bot.start()
  File "./rtmbot.py", line 35, in start
    self.input(reply)
  File "./rtmbot.py", line 54, in input
    plugin.do(function_name, data)
  File "./rtmbot.py", line 121, in do
    eval("self.module." + function_name)(data)
  File "/Users/kosyanyanwu/workspace/food-bot-review/plugins/food_bot_plugin.py", line 27, in process_message
    buff = str(data['text']).split(' ')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 21: ordinal not in range(128)
```

**Comment by andela-kanyanwu** [comment]
Issue fixed and deployed.
