### ISSUE TITLE
Foodbot gives no response when you rate

### ISSUE THREAD

**Issue by andela-kanyanwu** [andela-kanyanwu/food-bot-review#62]
Traceback (most recent call last):
  File "./rtmbot.py", line 181, in main_loop
    bot.start()
  File "./rtmbot.py", line 35, in start
    self.input(reply)
  File "./rtmbot.py", line 54, in input
    plugin.do(function_name, data)
  File "./rtmbot.py", line 121, in do
    eval("self.module." + function_name)(data)
  File "/Users/kosyanyanwu/workspace/food-bot-review/plugins/food_bot_plugin.py", line 40, in process_message
    Response.rate(channel, buff, user_id)
  File "/Users/kosyanyanwu/workspace/food-bot-review/plugins/food_bot_plugin.py", line 204, in rate
    rate_context_dict = Helper.get_rate_template_context(buff, user_id)
  File "/Users/kosyanyanwu/workspace/food-bot-review/plugins/food_bot_plugin.py", line 186, in get_rate_template_context
    sql.command(query_string, variables)
  File "/Users/kosyanyanwu/workspace/food-bot-review/custom_sql.py", line 43, in command
    self.cursor.execute(query_string, variables)
IntegrityError: null value in column "date" violates not-null constraint
DETAIL:  Failing row contains (1, null, U0774N56J, 4, The stew was nice today., 70).

**Comment by andela-kanyanwu** [comment]
Issue resolved.
